### ISSUE TITLE
Should this line be self.transforms.set_mode("train")?

### ISSUE THREAD

**Issue by ElviraLL** [gorodnitskiy/yet-another-lightning-hydra-template#3]
https://github.com/gorodnitskiy/yet-another-lightning-hydra-template/blob/936e99fd6c9d033b4f407b96370fd64656566874/src/datamodules/mnist_datamodule.py#L34

**Comment by gorodnitskiy** [comment]
Thank you for bringing up this issue!

You're correct that `TransformsWrapper` should be set up to apply transformations for training. However, this code specified only for testing. I am using the MNIST dataset which includes separate train and test sets, and then I concatenate these sets for splitting them into new train, validation, and test sets, which required for testing of different code parts (see more in `tests/`). So, in this context, the exact mode of `TransformsWrapper` is not critical in `MNISTDataModule` class, as the transformations applied to the initial MNIST sets are the same (see more in `configs/datamodule/mnist.yaml`) due to further splitting.

I realize that this might not be clear from the code. To improve clarity, I added a comment explaining why the same transformations are used, and changed the mode name to "train". I hope it will help avoid any misunderstanding.

The main logic of `DataModule` in this pipeline could be seen in `src/datamodules/datamodules.py`. `MNISTDataModule` is used just for testing.

Thank you for your contribution to improving the quality and clarity of this project. If you have any further questions or suggestions, feel free to share!
